name: CI

on: [push]

env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        
jobs:
  
  build:
    runs-on: ubuntu-latest
    container: unityci/editor:2020.1.14f1-windows-mono-0
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1

        # - name: Decrypt the license file
          # run: openssl aes-256-cbc -d -in .github/Unity_v2020.x.ulf.enc -k ${{ secrets.UNITY_LICENSE_DECRYPT_KEY }} >> .github/Unity_v2020.x.ulf
        
        # # Activate unity
        # - name: Activate Unity
          # run: /opt/unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .github/Unity_v2020.x.ulf || exit 0
        
        # Activate unity - step 1
        - name: Activate Unity - step 1
          run: echo '${{ secrets.UNITY_LICENSE }}' > License.ulf
        
        - name: Activate Unity
          run: /opt/unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .github/License.ulf || exit 0
          
